#!/bin/bash

# format untracked files
git ls-files --others --exclude-standard | xargs dotnet format

# format tracked files that still exist
git status --porcelain | awk 'match($1, "M"){print $2}' | dotnet format

# todo: reconfigure for "dotnet csharpier format"