name: Debug Build (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build (Debug)
        run: dotnet run --project src/FlossApp.Wasm/FlossApp.Wasm.csproj --configuration Debug
